#development
deployment:
  user: team0616
  from: ./
  to: /var/www/html/beacode_dev/
  excludes:
    - .idea
    - var/cache/*
    - var/logs/*
    - var/sessions/*
    - app/config/parameters.yml
    - files/*
  strategy: targz

releases:
  enabled: true
  max: 3
  symlink: current
  directory: releases

hosts:
  - team06-16.studenti.fiit.stuba.sk
#  - 147.175.149.218

tasks:
  pre-deploy:
  on-deploy:
    - shared-folder-task: {sharedFiles: 'app/config/parameters.yml'}
    - doctrine-schema-update-task
    - cache-clear-task: {env: dev}
    - cache-clear-task: {env: prod}
    - permissions-task
  post-release:
  post-deploy:
