beacode_api_admin_web_events_show:
    path:     /api/admin-web/events
    defaults: { _controller: BeacodeAdminWebBundle:Event:showEvents }
    methods:  [GET, OPTIONS]

beacode_api_admin_web_events_show_one:
    path:     /api/admin-web/events/{eventId}
    defaults: { _controller: BeacodeAdminWebBundle:Event:showEvent }
    methods:  [GET, OPTIONS]

beacode_api_admin_web_events_save:
    path:     /api/admin-web/events/new
    defaults: { _controller: BeacodeAdminWebBundle:Event:saveEvent }
    methods:  [POST, OPTIONS]

#***********************************************************************************************************************

beacode_api_admin_web_events_exhibits_show:
    path:     /api/admin-web/events/{eventId}/exhibits
    defaults: { _controller: BeacodeAdminWebBundle:Exhibit:showEventsExhibits }
    methods:  [GET, OPTIONS]

beacode_api_admin_web_events_exhibits_save:
    path:     /api/admin-web/events/{eventId}/exhibits/new
    defaults: { _controller: BeacodeAdminWebBundle:Exhibit:saveEventsExhibit }
    methods:  [POST, OPTIONS]

#***********************************************************************************************************************

beacode_api_admin_web_locations_show:
    path:     /api/admin-web/locations
    defaults: { _controller: BeacodeAdminWebBundle:Location:showLocations }
    methods:  [POST, OPTIONS]

#***********************************************************************************************************************

beacode_api_admin_web_beacons_show:
    path:     /api/admin-web/beacons
    defaults: { _controller: BeacodeAdminWebBundle:Beacon:showBeacons }
    methods:  [GET, OPTIONS]
