beacode_api_admin_web_liu_events_show:
    path:     /api/admin-web/liu/events
    defaults: { _controller: BeacodeAdminWebBundle:Event:showLiuEvents }
    methods:  [GET, OPTIONS]

beacode_api_admin_web_liu_events_save:
    path:     /api/admin-web/liu/events/new
    defaults: { _controller: BeacodeAdminWebBundle:Event:saveLiuEvent }
    methods:  [POST, OPTIONS]

#***********************************************************************************************************************

beacode_api_admin_web_events_exhibits_show:
    path:     /api/admin-web/events/{eventId}/exhibits
    defaults: { _controller: BeacodeAdminWebBundle:Exhibit:showEventsExhibits }
    methods:  [GET, OPTIONS]

beacode_api_admin_web_events_exhibits_save:
    path:     /api/admin-web/events/{eventId}/exhibits/new
    defaults: { _controller: BeacodeAdminWebBundle:Exhibit:saveEventsExhibit }
    methods:  [POST, OPTIONS]
