beacode_admin_web:
    resource: "@BeacodeAdminWebBundle/Resources/config/routing.yml"
    prefix:   /

beacode_app_ios:
    resource: "@BeacodeAppIOSBundle/Resources/config/routing.yml"
    prefix:   /

beacode_app_android:
    resource: "@BeacodeAppAndroidBundle/Resources/config/routing.yml"
    prefix:   /

beacode_core:
    resource: "@BeacodeCoreBundle/Resources/config/routing.yml"
    prefix:   /

