beacode_api_app_events_show:
    path:     /api/app/events
    defaults: { _controller: BeacodeAppBundle:Event:showEvents}
    methods:  [POST]

#***********************************************************************************************************************

beacode_api_app_starred_events_show:
    path:     /api/app/starred-events
    defaults: { _controller: BeacodeAppBundle:StarredEvent:showStarredEvents }
    methods:  [GET]

#***********************************************************************************************************************

beacode_api_app_events_exhibits_show:
    path:     /api/app/events/{eventId}/exhibits
    defaults: { _controller: BeacodeAppBundle:Exhibit:showEventsExhibits }
    methods:  [GET]

#***********************************************************************************************************************

beacode_api_app_interests_show:
    path:     /api/app/interests
    defaults: { _controller: BeacodeAppBundle:Interest:showInterests }
    methods:  [GET]

beacode_api_app_interests_save:
    path:     /api/app/interests/new
    defaults: { _controller: BeacodeAppBundle:Interest:saveInterest }
    methods:  [POST]

beacode_api_app_interests_delete:
    path:     /api/app/interests/{interestId}
    defaults: { _controller: BeacodeAppBundle:Interest:deleteInterest }
    methods:  [DELETE]

#***********************************************************************************************************************

beacode_api_app_logged_in_user_show:
    path:     /api/app/logged-in-user
    defaults: { _controller: BeacodeAppBundle:User:showLoggedInUser }
    methods:  [GET]

#***********************************************************************************************************************

beacode_api_app_events_selected_exhibits_for_tour_show:
    path:     /api/app/events/{eventId}/selected-exhibits-for-tour
    defaults: { _controller: BeacodeAppBundle:SelectedExhibitForTour:showEventsSelectedExhibitsForTour }
    methods:  [GET]

beacode_api_app_events_selected_exhibits_for_tour_save:
    path:     /api/app/events/{eventId}/selected-exhibits-for-tour/new
    defaults: { _controller: BeacodeAppBundle:SelectedExhibitForTour:saveEventsSelectedExhibitForTour }
    methods:  [POST]

beacode_api_app_events_selected_exhibits_for_tour_delete:
    path:     /api/app/events/{eventId}/selected-exhibits-for-tour/{selectedExhibitForTourId}
    defaults: { _controller: BeacodeAppBundle:SelectedExhibitForTour:deleteEventsSelectedExhibitForTour }
    methods:  [DELETE]

#***********************************************************************************************************************

beacode_api_app_logged_in_user_images_save:
    path:     /api/app/logged-in-user/images/new
    defaults: { _controller: BeacodeAppBundle:Image:saveLoggedInUserImage }
    methods:  [POST]
