beacode_api_app_events_show:
    path:     /api/app/events/show
    defaults: { _controller: BeacodeAppBundle:Core:showEvents}
    methods: [POST]

beacode_api_app_starred_events_show:
    path:     /api/app/starred-events/show
    defaults: { _controller: BeacodeAppBundle:Core:showStarredEvents }
    methods: [GET]

beacode_api_app_exhibits_show:
    path:     /api/app/exhibits/show/{eventId}
    defaults: { _controller: BeacodeAppBundle:Core:showExhibits }
    methods: [GET]

beacode_api_app_interests_show:
    path:     /api/app/interests/show
    defaults: { _controller: BeacodeAppBundle:Core:showInterests }
    methods: [GET]

