<?php

namespace Beacode\CoreBundle\Repository;
use Beacode\CoreBundle\Entity\Beacon;

/**
 * BeaconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeaconRepository extends CoreRepository {

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Beacon|int|null|object
     */
    public function createBeacon($data) {
        $object = new Beacon();
        $data['systemCreated'] = new \DateTime();
        $object = $this->getBeaconObjectFromData($object, $data);

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Beacon|int|null|object
     */
    public function createIfNotExistBeacon($data) {
        $object = $this->getBeacon($data);
        if (empty($object)) {
            $object = $this->createBeacon($data);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Beacon|null $object
     * @return Beacon|int|null|object
     */
    public function editBeacon($data, Beacon $object=null) {
        if (empty($object)) {
            $object = $this->getBeacon($data);
            if (empty($object)) return 0;
        }

        $object = $this->getBeaconObjectFromData($object, $data);

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Beacon|int|null|object
     */
    public function upsertBeacon($data) {
        $object = $this->getBeacon($data);
        if (empty($object)) {
            $object = $this->createBeacon($data);
        } else {
            $object = $this->editBeacon($data, $object);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Beacon|null $object
     * @return int
     */
    public function removeBeacon($data, Beacon $object=null) {
        if (empty($object)) {
            $object = $this->getBeacon($data);
            if (empty($object)) return 0;
        }

        $this->_em->remove($object);

        $this->_em->flush();

        return 1;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return null|object
     */
    public function getBeacon($data) {
        $object = null;

        if (!empty($data['id'])) {
            $object = $this->findOneBy(['id'=>$data['id']]);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Beacon $object
     * @param $data
     * @return Beacon
     */
    private function getBeaconObjectFromData(Beacon $object, $data) {
        if (!empty($data['exhibitId'])) $object->setExhibitId($data['exhibitId']);
        if (!empty($data['UUID'])) $object->setUUID($data['UUID']);
        if (!empty($data['major'])) $object->setMajor($data['major']);
        if (!empty($data['minor'])) $object->setMinor($data['minor']);
        if (!empty($data['systemCreated'])) $object->setSystemCreated($data['systemCreated']);

        $this->_em->persist($object);

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Beacon $object
     * @param $forFunction
     * @return array
     */
    public function getBeaconDataFromObject(Beacon $object, $forFunction) {
        $whichData = [];
        if ($forFunction == 1) $whichData = [1];

        $data = [];
        if (in_array(1, $whichData)) {
            $data['id'] = $object->getId();
        }
        if (in_array(2, $whichData)) {
            $data['UUID'] = $object->getUUID();
            $data['major'] = $object->getMajor();
            $data['minor'] = $object->getMinor();
        }

        return $data;
    }

    //******************************************************************************************************************
    //******************************************************************************************************************
}
