<?php

namespace Beacode\CoreBundle\Repository;
use Beacode\CoreBundle\Entity\Event;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Event|int|null|object
     */
    public function createEvent($data) {
        $object = new Event();
        $data['systemCreated'] = new \DateTime();
        $object = $this->getEventObjectFromData($object, $data);

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Event|int|null|object
     */
    public function createIfNotExistEvent($data) {
        $object = $this->getEvent($data);
        if (empty($object)) {
            $object = $this->createEvent($data);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Event|null $object
     * @return Event|int|null|object
     */
    public function editEvent($data, Event $object=null) {
        if (empty($object)) {
            $object = $this->getEvent($data);
            if (empty($object)) return 0;
        }

        $object = $this->getEventObjectFromData($object, $data);

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Event|int|null|object
     */
    public function upsertEvent($data) {
        $object = $this->getEvent($data);
        if (empty($object)) {
            $object = $this->createEvent($data);
        } else {
            $object = $this->editEvent($data, $object);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Event|null $object
     * @return int
     */
    public function removeEvent($data, Event $object=null) {
        if (empty($object)) {
            $object = $this->getEvent($data);
            if (empty($object)) return 0;
        }

        $this->_em->remove($object);

        $this->_em->flush();

        return 1;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return null|object
     */
    public function getEvent($data) {
        $object = null;

        if (!empty($data['id'])) {
            $object = $this->findOneBy(['id'=>$data['id']]);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Event $object
     * @param $data
     * @return Event
     */
    private function getEventObjectFromData(Event $object, $data) {
        if (!empty($data['name'])) $object->setName($data['name']);
        if (!empty($data['start'])) $object->setStart($data['start']);
        if (!empty($data['end'])) $object->setEnd($data['end']);
        if (!empty($data['location'])) $object->setLocation($data['location']);
        if (!empty($data['description'])) $object->setDescription($data['description']);
        if (!empty($data['systemCreated'])) $object->setSystemCreated($data['systemCreated']);

        $this->_em->persist($object);

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Event $object
     * @param $forFunction
     * @return array
     */
    public function getEventDataFromObject(Event $object, $forFunction) {
        $whichData = [];
        if ($forFunction == 1) $whichData = [1];

        $data = [];
        if (in_array(1, $whichData)) {
            $data['id'] = $object->getId();
        }
        if (in_array(2, $whichData)) {
            $data['name'] = $object->getName();
            $data['start'] = $object->getStart();
            $data['end'] = $object->getEnd();
            $data['location'] = $object->getLocation();
            $data['description'] = $object->getDescription();
        }

        return $data;
    }
}
