<?php

namespace Beacode\CoreBundle\Repository;
use Beacode\CoreBundle\Entity\Exhibit;

/**
 * ExhibitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitRepository extends CoreRepository {

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Exhibit|int|null|object
     */
    public function createExhibit($data) {
        $object = new Exhibit();
        $data['systemCreated'] = new \DateTime();
        $object = $this->getExhibitObjectFromData($object, $data);
        if ($this->isError($object)) return $object;

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Exhibit|int|null|object
     */
    public function createIfNotExistExhibit($data) {
        $object = $this->getExhibit($data);
        if (empty($object)) {
            $object = $this->createExhibit($data);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Exhibit|null $object
     * @return Exhibit|int|null|object
     */
    public function editExhibit($data, Exhibit $object=null) {
        if (empty($object)) {
            $object = $this->getExhibit($data);
            if ($this->isError($object)) return $object;
        }

        $object = $this->getExhibitObjectFromData($object, $data);
        if ($this->isError($object)) return $object;

        $this->_em->flush();

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return Exhibit|int|null|object
     */
    public function upsertExhibit($data) {
        $object = $this->getExhibit($data);
        if (empty($object)) {
            $object = $this->createExhibit($data);
        } else {
            $object = $this->editExhibit($data, $object);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param Exhibit|null $object
     * @return int
     */
    public function removeExhibit($data, Exhibit $object=null) {
        if (empty($object)) {
            $object = $this->getExhibit($data);
            if ($this->isError($object)) return $object;
        }

        //beacons set null
        $beaconObjectArray = $this->getRepo('Beacon')->findBy(['exhibitId'=>$object->getId()]);
        foreach ($beaconObjectArray as $beaconObject) {
            $this->getRepo('Beacon')->editBeacon(['exhibitId'=>null], $beaconObject);
        }

        //images cascade
        $imageObjectArray = $this->getRepo('Image')->findBy(['objectId'=>$object->getId(), 'objectType'=>'exhibit']);
        foreach ($imageObjectArray as $imageObject) {
            $this->getRepo('Image')->removeImage([], $imageObject);
        }

        //selectedExhibitForTours cascade
        $selectedExhibitForTourObjectArray = $this->getRepo('SelectedExhibitForTour')->findBy(['exhibitId'=>$object->getId()]);
        foreach ($selectedExhibitForTourObjectArray as $selectedExhibitForTourObject) {
            $this->getRepo('SelectedExhibitForTour')->removeSelectedExhibitForTour([], $selectedExhibitForTourObject);
        }

        $this->_em->remove($object);

        $this->_em->flush();

        return 1;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return int|null|object
     */
    public function getExhibit($data) {
        if (!empty($data['id'])) {
            $object = $this->findOneBy(['id'=>$data['id']]);
        }

        if (empty($object)) return 0;
        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Exhibit $object
     * @param $data
     * @return Exhibit|int
     */
    private function getExhibitObjectFromData(Exhibit $object, $data) {
        if (!empty($data['eventId'])) $object->setEventId($data['eventId']);
        if (!empty($data['name'])) $object->setName($data['name']);
        if (!empty($data['description'])) $object->setDescription($data['description']);
        if (!empty($data['systemCreated'])) $object->setSystemCreated($data['systemCreated']);
        if (!empty($data['start'])) $object->setStart($data['start']);
        if (!empty($data['end'])) $object->setEnd($data['end']);

        if (!$this->isExhibitObjectConsistent($object)) return -1;

        $this->_em->persist($object);

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Exhibit $object
     * @return bool
     */
    private function isExhibitObjectConsistent(Exhibit $object) {
        if (empty($object->getEventId())) return false;
        if (empty($object->getName())) return false;
        if (empty($object->getDescription())) return false;
        if (empty($object->getSystemCreated())) return false;
        return true;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param Exhibit $object
     * @param $forFunction
     * @param array $dataIn
     * @return array|int
     */
    public function getExhibitDataFromObject(Exhibit $object=null, $forFunction, $dataIn=[]) {
        if (empty($object)) {
            $object = $this->getExhibit($dataIn);
            if ($this->isError($object)) return $object;
        }

        $whichData = [];
        if ($forFunction == 1) $whichData = [1, 3, 4, 5];
        else if ($forFunction == 2) $whichData = [1];

        $data = [];
        if (in_array(1, $whichData)) {
            $data['id'] = $object->getId();
        }
        if (in_array(2, $whichData)) {
            $data['eventId'] = $object->getEventId();
        }
        if (in_array(3, $whichData)) {
            $data['name'] = $object->getName();
        }
        if (in_array(4, $whichData)) {
            $data['description'] = $object->getDescription();
        }
        if (in_array(5, $whichData)) {
            $data['start'] = null;
            if (!empty($object->getStart())) $data['start'] = $object->getStart()->format('d.m.Y H:i');
            $data['end'] = null;
            if (!empty($object->getEnd())) $data['end'] = $object->getEnd()->format('d.m.Y H:i');
        }

        return $data;
    }

    //******************************************************************************************************************

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return mixed
     */
    public function getImagesForId($data) {
        $imageObjectArray = $this->getRepo('Image')->findBy(['objectId'=>$data['id'], 'objectType'=>'exhibit']);

        foreach ($imageObjectArray as $imageObject) {
            $data['images'][] = $this->getRepo('Image')->getImageDataFromObject($imageObject, 1);
        }

        return $data;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return mixed
     */
    public function getBeaconsForId($data) {
        $beaconObjectArray = $this->getRepo('Beacon')->findBy(['exhibitId'=>$data['id']]);

        foreach ($beaconObjectArray as $beaconObject) {
            $data['beacons'][] = $this->getRepo('Beacon')->getBeaconDataFromObject($beaconObject, 1);
        }

        return $data;
    }

    //******************************************************************************************************************
    //******************************************************************************************************************

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function showAppEventsExhibits($data) {
        $exhibitObjectArray = $this->findBy(['eventId'=>$data['eventId']], ['name'=>'ASC']);

        $exhibitDataArray = [];
        foreach ($exhibitObjectArray as $key=>$exhibitObject) {
            $exhibitDataArray[$key] = $this->getExhibitDataFromObject($exhibitObject, 1);
            $exhibitDataArray[$key] = $this->getImagesForId($exhibitDataArray[$key]);
            $exhibitDataArray[$key] = $this->getBeaconsForId($exhibitDataArray[$key]);
        }

        return ['result'=>1, 'data'=>$exhibitDataArray];
    }

    //******************************************************************************************************************
    //******************************************************************************************************************

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function showAdminWebEventsExhibits($data) {
        return $this->showAppEventsExhibits($data);
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function saveAdminWebEventsExhibit($data) {
        if (!empty($data['start'])) $data['start'] = new \DateTime($data['start']);
        if (!empty($data['end'])) $data['end'] = new \DateTime($data['end']);
        $exhibitObject = $this->createIfNotExistExhibit($data);
        if ($this->isError($exhibitObject)) return ['result'=>$exhibitObject];

        $exhibitData = $this->getExhibitDataFromObject($exhibitObject, 2);

        return ['result'=>1, 'data'=>$exhibitData];
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function deleteAdminWebEventsExhibit($data) {
        $exhibitObject = $this->getExhibit($data);
        if ($this->isError($exhibitObject)) return ['result'=>$exhibitObject];

        $result = $this->removeExhibit($data, $exhibitObject);

        return ['result'=>$result];
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @param $patchArray
     * @return array
     */
    public function changeAdminWebEventsExhibit($data, $patchArray) {
        $exhibitObject = $this->getExhibit($data);
        if ($this->isError($exhibitObject)) return ['result'=>$exhibitObject];

        foreach ($patchArray as $patch) {
            $pathArray = explode('/', $patch['path']);
            if ($patch['op'] == 'replace') {
                $data[$pathArray[1]] = $patch['value'];
            }
        }

        $exhibitObject = $this->editExhibit($data, $exhibitObject);
        if ($this->isError($exhibitObject)) return ['result'=>$exhibitObject];

        return ['result'=>1];
    }
}
