<?php

namespace Beacode\CoreBundle\Repository;

/**
 * ExhibitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitRepository extends \Doctrine\ORM\EntityRepository {

}
