<?php

namespace Beacode\CoreBundle\Repository;

/**
 * SelectedExhibitForTourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectedExhibitForTourRepository extends \Doctrine\ORM\EntityRepository {

}
