<?php

namespace Beacode\CoreBundle\Repository;

/**
 * StarredEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarredEventRepository extends \Doctrine\ORM\EntityRepository {

}
