<?php

namespace Beacode\UserBundle\Repository;
use Beacode\CoreBundle\Repository\CoreRepository;
use Beacode\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CoreRepository  {

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return int|null|object
     */
    public function getUser($data) {
        if (!empty($data['id'])) {
            $object = $this->findOneBy(['id'=>$data['id']]);
        }

        if (empty($object)) return 0;
        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param User|null $object
     * @param $forFunction
     * @param array $dataIn
     * @return array|User|int|null|object
     */
    public function getUserDataFromObject(User $object=null, $forFunction, $dataIn=[]) {
        if (empty($object)) {
            $object = $this->getUser($dataIn);
            if (is_int($object)) return $object;
        }

        $whichData = [];
        if ($forFunction == 1) $whichData = [1, 2];

        $data = [];
        if (in_array(1, $whichData)) {
            $data['id'] = $object->getId();
        }
        if (in_array(2, $whichData)) {
            $data['firstName'] = $object->getFirstName();
            $data['lastName'] = $object->getLastName();
        }

        return $data;
    }

    //******************************************************************************************************************
    //******************************************************************************************************************

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function showLoggedInUser($data) {
        $userData = $this->getUserDataFromObject(null, 1, $data);
        if (is_int($userData)) return ['result'=>$userData];

        return ['result'=>1, 'data'=>$userData];
    }
}
