<?php

namespace Beacode\UserBundle\Repository;
use Beacode\CoreBundle\Repository\CoreRepository;
use Beacode\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CoreRepository  {

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return null|object
     */
    public function getUser($data) {
        $object = null;

        if (!empty($data['id'])) {
            $object = $this->findOneBy(['id'=>$data['id']]);
        }

        return $object;
    }

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param User $object
     * @param $forFunction
     * @return array
     */
    public function getUserDataFromObject(User $object, $forFunction) {
        $whichData = [];
        if ($forFunction == 1) $whichData = [1, 2];

        $data = [];
        if (in_array(1, $whichData)) {
            $data['id'] = $object->getId();
        }
        if (in_array(2, $whichData)) {
            $data['firstName'] = $object->getFirstName();
            $data['lastName'] = $object->getLastName();
        }

        return $data;
    }

    //******************************************************************************************************************
    //******************************************************************************************************************

    /**
     * @author Juraj Flamik <juraj.flamik@gmail.com>
     * @param $data
     * @return array
     */
    public function showLoggedInUser($data) {
        $userObject = $this->getUser($data);
        if (empty($userObject)) return ['result'=>0];
        $userData = $this->getUserDataFromObject($userObject, 1);

        return ['result'=>1, 'data'=>$userData];
    }
}
